apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:5.3.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 2888
        volumeMounts:
        - name: zookeeper
          mountPath: /var/lib/zookeeper/data
          subPath: data
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2888"
  volumeClaimTemplates:
  - metadata:
      name: zookeeper
    spec:
      resources:
        requests:
          storage: 5Gi
      accessModes:
      - ReadWriteMany
      volumeName: zookeeper
      volumeMode: Filesystem
