apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-headless
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:5.3.1
        imagePullPolicy: Always
        ports:
        - name: server
          containerPort: 2888
        - name: leader-election
          containerPort: 3888
        - name: client
          containerPort: 2181
        volumeMounts:
        - name: zookeeper
          mountPath: /var/lib/zookeeper/data
          subPath: data
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name : KAFKA_HEAP_OPTS
          value: "-Xms512M -Xmx512M"
        - name : ZOOKEEPER_TICK_TIME
          value: "2000"
        - name : ZOOKEEPER_SYNC_LIMIT
          value: "5"
        - name : ZOOKEEPER_INIT_LIMIT
          value: "10"
        - name : ZOOKEEPER_MAX_CLIENT_CNXNS
          value: "60"
        - name : ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
          value: "3"
        - name : ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
          value: "24"
        - name : ZOOKEEPER_SERVERS
          value: "zookeeper-0.zookeeper-headless.enedi-infra.svc.cluster.local:2888:3888"
        - name: ZOOKEEPER_SERVER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - "bash"
        - "-c"
        - |
          ZK_FIX_HOST_REGEX="s/${HOSTNAME}\.[^:]*:/0.0.0.0:/g"
          ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1)) \
          ZOOKEEPER_SERVERS=`echo $ZOOKEEPER_SERVERS | sed -e "$ZK_FIX_HOST_REGEX"` \
          /etc/confluent/docker/run
  volumeClaimTemplates:
  - metadata:
      name: zookeeper
    spec:
      resources:
        requests:
          storage: 5Gi
      accessModes:
      - ReadWriteMany
      volumeName: zookeeper
      volumeMode: Filesystem
