apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:5.3.1
        ports:
        - name: schema-registry
          containerPort: 8081
        imagePullPolicy: IfNotPresent
        env:
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: "zookeeper.enedi-infra.svc.cluster.local:2181"
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        # command:
        # - sh
        # - -exc
        # - |
        #   export SCHEMA_REGISTRY_HOST_NAME=${HOSTNAME}
