apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:5.3.1
        ports:
        - name: control-center
          containerPort: 9021
        imagePullPolicy: IfNotPresent
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "kafka-0.kafka-headless.enedi-infra:9092"
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: "zookeeper.enedi-infra.svc.cluster.local:2181"
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value: "kafka-connect-service.enedi-infra.svc.cluster.local:8083"
        - name: CONTROL_CENTER_KSQL_URL
          value: "http://ksql-server-service.enedi-infra.svc.cluster.local:8088"
        - name: CONTROL_CENTER_KSQL_ADVERTISED_URL
          value: "http://ksql-server-service.enedi-infra.svc.cluster.local:8088"
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-service.enedi-infra.svc.cluster.local:8081"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "9021"
