apiVersion: v1
kind: Service
metadata:
  name: ksql-external-server
spec:
  type: NodePort
  selector:
    app: ksql-server
  ports:
  - name: ksql-server-external
    port: 8088
    nodePort: 31088
    targetPort: 8088
    protocol: TCP
    
